# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(897, 528)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("traceIcon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filename = QtWidgets.QLabel(self.tab_2)
        self.filename.setObjectName("filename")
        self.horizontalLayout.addWidget(self.filename)
        self.btn_file = QtWidgets.QPushButton(self.tab_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_file.setIcon(icon1)
        self.btn_file.setObjectName("btn_file")
        self.horizontalLayout.addWidget(self.btn_file)
        self.btn_reload = QtWidgets.QPushButton(self.tab_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_reload.setIcon(icon2)
        self.btn_reload.setObjectName("btn_reload")
        self.horizontalLayout.addWidget(self.btn_reload)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.btn_preprocessor = QtWidgets.QPushButton(self.tab_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("work.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_preprocessor.setIcon(icon3)
        self.btn_preprocessor.setObjectName("btn_preprocessor")
        self.verticalLayout_9.addWidget(self.btn_preprocessor)
        self.widget_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fileview = QtWidgets.QGraphicsView(self.widget)
        self.fileview.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.fileview.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.fileview.setObjectName("fileview")
        self.verticalLayout_5.addWidget(self.fileview)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.display_draw_steps = QtWidgets.QCheckBox(self.widget_5)
        self.display_draw_steps.setObjectName("display_draw_steps")
        self.horizontalLayout_8.addWidget(self.display_draw_steps)
        self.redraw = QtWidgets.QPushButton(self.widget_5)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("writing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redraw.setIcon(icon4)
        self.redraw.setObjectName("redraw")
        self.horizontalLayout_8.addWidget(self.redraw)
        self.verticalLayout_5.addWidget(self.widget_5)
        self.horizontalLayout_5.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.code_edit = QtWidgets.QTextEdit(self.widget_3)
        self.code_edit.setObjectName("code_edit")
        self.verticalLayout.addWidget(self.code_edit)
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_save_file = QtWidgets.QPushButton(self.widget_4)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save_file.setIcon(icon5)
        self.btn_save_file.setObjectName("btn_save_file")
        self.horizontalLayout_7.addWidget(self.btn_save_file)
        self.btn_save_as = QtWidgets.QPushButton(self.widget_4)
        self.btn_save_as.setIcon(icon5)
        self.btn_save_as.setObjectName("btn_save_as")
        self.horizontalLayout_7.addWidget(self.btn_save_as)
        self.verticalLayout.addWidget(self.widget_4)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.verticalLayout_9.addWidget(self.widget_2)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.serial_monitor = QtWidgets.QTextEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_monitor.sizePolicy().hasHeightForWidth())
        self.serial_monitor.setSizePolicy(sizePolicy)
        self.serial_monitor.setMinimumSize(QtCore.QSize(0, 300))
        self.serial_monitor.setMaximumSize(QtCore.QSize(16777215, 2000))
        self.serial_monitor.setStyleSheet("background-color:black;")
        self.serial_monitor.setReadOnly(True)
        self.serial_monitor.setObjectName("serial_monitor")
        self.verticalLayout_2.addWidget(self.serial_monitor)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.command_edit = QtWidgets.QLineEdit(self.groupBox)
        self.command_edit.setObjectName("command_edit")
        self.horizontalLayout_4.addWidget(self.command_edit)
        self.btn_command = QtWidgets.QPushButton(self.groupBox)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_command.setIcon(icon6)
        self.btn_command.setObjectName("btn_command")
        self.horizontalLayout_4.addWidget(self.btn_command)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_serie = QtWidgets.QWidget()
        self.tab_serie.setObjectName("tab_serie")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_serie)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.serial_settings = QtWidgets.QFormLayout()
        self.serial_settings.setObjectName("serial_settings")
        self.label = QtWidgets.QLabel(self.tab_serie)
        self.label.setObjectName("label")
        self.serial_settings.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.baudrate = QtWidgets.QComboBox(self.tab_serie)
        self.baudrate.setObjectName("baudrate")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.baudrate.addItem("")
        self.serial_settings.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.baudrate)
        self.portSRieLabel = QtWidgets.QLabel(self.tab_serie)
        self.portSRieLabel.setObjectName("portSRieLabel")
        self.serial_settings.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.portSRieLabel)
        self.serial_ports_list = QtWidgets.QComboBox(self.tab_serie)
        self.serial_ports_list.setObjectName("serial_ports_list")
        self.serial_settings.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.serial_ports_list)
        self.btn_serial_ports_list = QtWidgets.QPushButton(self.tab_serie)
        self.btn_serial_ports_list.setObjectName("btn_serial_ports_list")
        self.serial_settings.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.btn_serial_ports_list)
        self.label_5 = QtWidgets.QLabel(self.tab_serie)
        self.label_5.setObjectName("label_5")
        self.serial_settings.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.timeout_read = QtWidgets.QSpinBox(self.tab_serie)
        self.timeout_read.setMaximum(1000)
        self.timeout_read.setProperty("value", 100)
        self.timeout_read.setObjectName("timeout_read")
        self.serial_settings.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.timeout_read)
        self.utiliserFichierLogTxtLabel = QtWidgets.QLabel(self.tab_serie)
        self.utiliserFichierLogTxtLabel.setObjectName("utiliserFichierLogTxtLabel")
        self.serial_settings.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.utiliserFichierLogTxtLabel)
        self.use_log = QtWidgets.QCheckBox(self.tab_serie)
        self.use_log.setObjectName("use_log")
        self.serial_settings.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.use_log)
        self.verticalLayout_3.addLayout(self.serial_settings)
        self.btn_connect = QtWidgets.QPushButton(self.tab_serie)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_connect.setIcon(icon7)
        self.btn_connect.setObjectName("btn_connect")
        self.verticalLayout_3.addWidget(self.btn_connect)
        self.tabWidget.addTab(self.tab_serie, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.send_manual_cmd = QtWidgets.QCheckBox(self.tab)
        self.send_manual_cmd.setObjectName("send_manual_cmd")
        self.verticalLayout_8.addWidget(self.send_manual_cmd)
        self.grp_plan = QtWidgets.QGroupBox(self.tab)
        self.grp_plan.setObjectName("grp_plan")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.grp_plan)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_y_plus = QtWidgets.QPushButton(self.grp_plan)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_y_plus.setIcon(icon8)
        self.btn_y_plus.setObjectName("btn_y_plus")
        self.gridLayout_2.addWidget(self.btn_y_plus, 0, 1, 1, 1)
        self.btn_x_plus = QtWidgets.QPushButton(self.grp_plan)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_x_plus.setIcon(icon9)
        self.btn_x_plus.setObjectName("btn_x_plus")
        self.gridLayout_2.addWidget(self.btn_x_plus, 1, 2, 1, 1)
        self.btn_y_minus = QtWidgets.QPushButton(self.grp_plan)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_y_minus.setIcon(icon10)
        self.btn_y_minus.setObjectName("btn_y_minus")
        self.gridLayout_2.addWidget(self.btn_y_minus, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.grp_plan)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 3, 1, 1)
        self.btn_x_minus = QtWidgets.QPushButton(self.grp_plan)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_x_minus.setIcon(icon11)
        self.btn_x_minus.setObjectName("btn_x_minus")
        self.gridLayout_2.addWidget(self.btn_x_minus, 1, 0, 1, 1)
        self.step_x = QtWidgets.QDoubleSpinBox(self.grp_plan)
        self.step_x.setObjectName("step_x")
        self.gridLayout_2.addWidget(self.step_x, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.grp_plan)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 3, 1, 1)
        self.step_y = QtWidgets.QDoubleSpinBox(self.grp_plan)
        self.step_y.setObjectName("step_y")
        self.gridLayout_2.addWidget(self.step_y, 2, 4, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.verticalLayout_8.addWidget(self.grp_plan)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.grp_z = QtWidgets.QGroupBox(self.tab)
        self.grp_z.setFlat(False)
        self.grp_z.setCheckable(False)
        self.grp_z.setObjectName("grp_z")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.grp_z)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_set_z_low = QtWidgets.QPushButton(self.grp_z)
        self.btn_set_z_low.setIcon(icon4)
        self.btn_set_z_low.setIconSize(QtCore.QSize(64, 64))
        self.btn_set_z_low.setObjectName("btn_set_z_low")
        self.horizontalLayout_6.addWidget(self.btn_set_z_low)
        self.btn_set_z_high = QtWidgets.QPushButton(self.grp_z)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("not_writing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_set_z_high.setIcon(icon12)
        self.btn_set_z_high.setIconSize(QtCore.QSize(64, 64))
        self.btn_set_z_high.setObjectName("btn_set_z_high")
        self.horizontalLayout_6.addWidget(self.btn_set_z_high)
        self.horizontalLayout_3.addWidget(self.grp_z)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.btn_go_to_zero = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_go_to_zero.sizePolicy().hasHeightForWidth())
        self.btn_go_to_zero.setSizePolicy(sizePolicy)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("origin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_go_to_zero.setIcon(icon13)
        self.btn_go_to_zero.setIconSize(QtCore.QSize(64, 64))
        self.btn_go_to_zero.setFlat(False)
        self.btn_go_to_zero.setObjectName("btn_go_to_zero")
        self.verticalLayout_8.addWidget(self.btn_go_to_zero)
        self.btn_send_current_file = QtWidgets.QPushButton(self.tab)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_send_current_file.setIcon(icon14)
        self.btn_send_current_file.setObjectName("btn_send_current_file")
        self.verticalLayout_8.addWidget(self.btn_send_current_file)
        self.tabWidget.addTab(self.tab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.verticalLayout_4.addWidget(self.tabWidget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionRedraw = QtWidgets.QAction(MainWindow)
        self.actionRedraw.setObjectName("actionRedraw")
        self.actionReload = QtWidgets.QAction(MainWindow)
        self.actionReload.setObjectName("actionReload")

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.baudrate.setCurrentIndex(4)
        self.command_edit.returnPressed.connect(self.btn_command.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trace"))
        self.filename.setText(_translate("MainWindow", "Pas de fichier"))
        self.btn_file.setText(_translate("MainWindow", "Choisir le fichier"))
        self.btn_reload.setText(_translate("MainWindow", "Recharger"))
        self.btn_preprocessor.setText(_translate("MainWindow", "Utiliser le préprocesseur sur le fichier"))
        self.display_draw_steps.setText(_translate("MainWindow", "Afficher les étapes"))
        self.redraw.setText(_translate("MainWindow", "Redessiner"))
        self.btn_save_file.setText(_translate("MainWindow", "Enregistrer"))
        self.btn_save_as.setText(_translate("MainWindow", "Enregister sous..."))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Fichier"))
        self.groupBox.setTitle(_translate("MainWindow", "Moniteur série"))
        self.serial_monitor.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Commande :"))
        self.btn_command.setText(_translate("MainWindow", "Envoyer"))
        self.label.setText(_translate("MainWindow", "Baudrate"))
        self.baudrate.setItemText(0, _translate("MainWindow", "300"))
        self.baudrate.setItemText(1, _translate("MainWindow", "1200"))
        self.baudrate.setItemText(2, _translate("MainWindow", "2400"))
        self.baudrate.setItemText(3, _translate("MainWindow", "4800"))
        self.baudrate.setItemText(4, _translate("MainWindow", "9600"))
        self.baudrate.setItemText(5, _translate("MainWindow", "19200"))
        self.baudrate.setItemText(6, _translate("MainWindow", "38400"))
        self.baudrate.setItemText(7, _translate("MainWindow", "57600"))
        self.baudrate.setItemText(8, _translate("MainWindow", "115200"))
        self.baudrate.setItemText(9, _translate("MainWindow", "230400"))
        self.baudrate.setItemText(10, _translate("MainWindow", "250000"))
        self.portSRieLabel.setText(_translate("MainWindow", "Port série"))
        self.btn_serial_ports_list.setText(_translate("MainWindow", "Lister les ports série"))
        self.label_5.setText(_translate("MainWindow", "Timeout (ms)"))
        self.utiliserFichierLogTxtLabel.setText(_translate("MainWindow", "Utiliser fichier log.txt"))
        self.btn_connect.setText(_translate("MainWindow", "Connecter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_serie), _translate("MainWindow", "Port série"))
        self.send_manual_cmd.setText(_translate("MainWindow", "Envoi de commandes manuelles"))
        self.grp_plan.setTitle(_translate("MainWindow", "Position dans le plan"))
        self.btn_y_plus.setText(_translate("MainWindow", "Y+"))
        self.btn_x_plus.setText(_translate("MainWindow", "X+"))
        self.btn_y_minus.setText(_translate("MainWindow", "Y-"))
        self.label_6.setText(_translate("MainWindow", "Pas x (mm) :"))
        self.btn_x_minus.setText(_translate("MainWindow", "X-"))
        self.label_7.setText(_translate("MainWindow", "Pas y (mm)"))
        self.grp_z.setTitle(_translate("MainWindow", "Axe Z"))
        self.btn_set_z_low.setText(_translate("MainWindow", "Position basse"))
        self.btn_set_z_high.setText(_translate("MainWindow", "Position haute"))
        self.btn_go_to_zero.setText(_translate("MainWindow", "Aller à la position\n"
"Zéro"))
        self.btn_send_current_file.setText(_translate("MainWindow", "Envoyer le fichier courrant"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Contrôles"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Port Série"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "SaveAs"))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionRedraw.setText(_translate("MainWindow", "Redraw"))
        self.actionRedraw.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.actionReload.setText(_translate("MainWindow", "Reload"))
        self.actionReload.setShortcut(_translate("MainWindow", "Ctrl+R"))

